Allow only a single input path for CPG generation
joernio/joern pull request #1521
Opened 2022-06-23 18:03 UTC by fabsx00

This is a simplification that I've wanted to bring in for a while and that has now become more important as we're fixing the FILENAME field to contain relative paths: CPGs should only be created from a single input file or input directory. If multiple projects are to be included in one CPG, the user can move them into a parent directory, but that shouldn't be of concern to us.

2022-06-23 19:34 UTC, mpollmeier approved these changes

2022-06-24 03:45 UTC, max-leuthaeuser requested changes

2022-06-24 03:45 UTC, max-leuthaeuser commented on joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala
> +    determine(inputPath, sourceFileExtensions)
`determine(Set(inputPath),...`

2022-06-24 08:30 UTC, max-leuthaeuser commented on joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala
> +    determine(inputPath, sourceFileExtensions)
```suggestion
    determine(Set(inputPath), sourceFileExtensions)
```

2022-06-27 09:59 UTC, merged