add SLF4J dependency
joernio/joern pull request #2215
Opened 2023-01-27 13:07 UTC by pr0me

This should fix joern exiting after throwing the warning discussed in #2206 by adding a `slf4j` dependency. 
This has been now reported from multiple sides.

2023-01-27 15:21 UTC, mpollmeier requested changes
Unfortunately it's not that easy. If we do this, then `slf4j-simple` becomes a joern dependency and everything downstream inherits it. That's a big no-no though, because downstream projects may likely already bring in other slf4j implementations (there's like 20...). And with this change it means they'll have two, and that's even worse than having exactly one...

2023-01-27 15:24 UTC, mpollmeier commented
To fix these warnings we need to add the dependency to the specific places that use it, e.g. the frontend that's being invoked in that ticket.

2023-01-27 16:04 UTC, pr0me commented
Okay I see, thanks for the heads-up!

If I recall correctly, I saw that error just on starting joern-shell, before any frontends are invoked. 
But I'll investigate more.

2023-01-27 16:30 UTC, mpollmeier commented
ouch, yes you're right... I'd say that's new.
I'll try to figure out when that started...

2023-01-27 16:34 UTC, mpollmeier commented
oh, looks like that's an slf4j v2 issue. some dependency upgraded slf4j to version 2.x and new the whole mess just got another dimension 😭 
gotta love this stuff, probably got enough material for a book by now. not a happy one though

anyway, thanks for the heads-up, i'll get this sorted

2023-01-30 08:52 UTC, mpollmeier commented
superseded by https://github.com/joernio/joern/pull/2215

2023-01-30 08:52 UTC, closed without merging