[rubysrc2cpg] Parser and ast changes for empty right hand side of association
joernio/joern pull request #3226
Opened 2023-07-25 11:46 UTC by karan-batavia

@xavierpinho, can you please review?

2023-07-25 11:50 UTC, xavierpinho requested changes

2023-07-25 11:50 UTC, xavierpinho commented on joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
> +  "method definition for association parameters" should {
nitpick: these are called mandatory parameters

2023-07-25 11:50 UTC, xavierpinho commented on joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
> +      println(cpg.call.name.l)
should remove these

2023-07-25 11:50 UTC, xavierpinho commented on joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
> +  "have correct structure when no RHS for an association as a parameter is provided" in {
also mandatory parameters

2023-07-25 12:22 UTC, karan-batavia commented
@xavierpinho , addressed your review.

2023-07-25 12:27 UTC, xavierpinho approved these changes

2023-07-25 12:27 UTC, xavierpinho commented on joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
> +    operatorNode.name shouldBe "<operator>.activeRecordAssociation"
Out of this PR's responsibility, but might as well take advantage of a sample at hands.

I think there shouldn't be an operator here. The sample `foo(bar:)` should mean the same as `foo(bar: bar)`, in which case there wouldn't be an operator, but rather a call to `bar`.

Do you have a different opinion?

2023-07-26 04:32 UTC, karan-batavia commented
@xavierpinho, if there are no blockers, can you please merge?

2023-07-26 08:42 UTC, xavierpinho commented
> @xavierpinho, if there are no blockers, can you please merge?

There are merge conflicts. Please rebase or merge with master and we should be good

2023-07-26 14:31 UTC, karan-batavia commented
@xavierpinho Merged master.

2023-07-26 15:43 UTC, merged