Simple return node handling
joernio/joern pull request #3556
Opened 2023-08-29 11:33 UTC by pandurangpatil

1. MethodReturn Node handling for single return type.
2. Refactored the code around `processTypeInfo` method.
3. Also removed unwanted white space between method name and `(` while generting the method signature. Made changes in unit tests to adjust to this change.

TODO:
1. Need to work on tuple handling.

2023-08-29 12:36 UTC, DavidBakerEffendi requested changes

2023-08-29 15:02 UTC, pandurangpatil commented on joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
> +        .getOrElse(("", methodReturnNode(funcDecl, Defines.voidTypeName)))
This string is used for formation of signature. In GO there is no Void or any keyword. Hence it's empty

2023-08-29 15:05 UTC, pandurangpatil commented on joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
> +          .map(x => {
done

2023-08-29 15:05 UTC, pandurangpatil commented on joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala
> +      // TODO: Touple handling needs to be done properly to return both the types.
done

2023-08-30 07:00 UTC, DavidBakerEffendi approved these changes

2023-08-30 07:00 UTC, merged