ignore case while matching excluded files
joernio/joern pull request #4697
Opened 2024-06-27 09:56 UTC by Ferada

Otherwise specifying one variant might not match the same file on e.g. Windows systems, when in fact it should match.

c.f. https://shiftleft.zendesk.com/agent/tickets/102700 and https://shiftleftsecurity.slack.com/archives/CE822HDC1/p1719386396027259

2024-06-27 16:11 UTC, max-leuthaeuser approved these changes

2024-07-02 10:53 UTC, max-leuthaeuser requested changes
We will have to do this differently.
Path insensitive comparison should only happen for Windows.

2024-07-02 11:48 UTC, ml86 approved these changes

2024-07-02 11:59 UTC, max-leuthaeuser approved these changes

2024-07-02 12:32 UTC, max-leuthaeuser commented
Side info: MacOS also has a case insensitive filesystem by default.

2024-07-02 14:24 UTC, merged