Mark php2cpg static init methods as external
joernio/joern pull request #4975
Opened 2024-09-27 14:49 UTC by johannescoetzee

This is a hack to fix an autofix issue. The `offset` and `offsetEnd` properties aren't set for the static init method since there aren't always sensible values to set these to, but since they weren't external, autofix was expecting this.

Some backend passes may be affected by this too

2024-09-27 15:25 UTC, max-leuthaeuser commented
I guess a valid alternative to this could be: set the same offsets as for the surrounding class. Hence, the whole class code would become the context.

2024-09-27 15:27 UTC, max-leuthaeuser approved these changes

2024-09-30 09:52 UTC, max-leuthaeuser requested changes
I guess a valid alternative to this could be: set the same offsets as for the surrounding class. Hence, the whole class code would become the context. Which is too much in general but may help autofix as more contextual info there is always better.

2024-09-30 10:05 UTC, johannescoetzee commented
I've set the offsets to the entire file as requested

2024-09-30 10:07 UTC, max-leuthaeuser approved these changes

2024-09-30 10:36 UTC, merged